/**
 * fixCategoriesAndPrices.js
 * - Adds products to all categories that have 0 products
 * - Updates any products with price=0 to a random realistic price
 * Safe to run multiple times (won't duplicate if products already exist)
 */
import dotenv from "dotenv";
import mongoose from "mongoose";

dotenv.config({
  path: new URL("../.env", import.meta.url).pathname.replace(
    /^\/([A-Z]:)/,
    "$1",
  ),
});

const MONGO_URI =
  process.env.MONGO_URI || "mongodb://127.0.0.1:27017/swiftpharma";

// ── Schema definitions (inline to avoid import path issues) ────────────────
const categorySchema = new mongoose.Schema(
  { name: String, slug: String, description: String },
  { timestamps: true },
);
const productSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    description: String,
    brand: String,
    manufacturer: String,
    composition: String,
    strength: String,
    packSize: String,
    price: { type: Number, required: true },
    mrp: Number,
    category: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    prescriptionRequired: { type: Boolean, default: false },
    isRx: { type: Boolean, default: false },
    requiresRx: { type: Boolean, default: false },
    stock: { type: Number, default: 0 },
    images: [String],
    sku: { type: String, unique: true, sparse: true },
  },
  { timestamps: true },
);

const Category = mongoose.model("Category", categorySchema);
const Product = mongoose.model("Product", productSchema);

// ── Seeding data per category slug ─────────────────────────────────────────
const CATEGORY_PRODUCTS = {
  "fever-pain-relief": [
    {
      name: "Paracetamol 500mg Tablet",
      composition: "Paracetamol",
      strength: "500mg",
      brand: "GSK",
      basePrice: 25,
      isRx: false,
      forms: ["Strip of 15 Tablets", "Bottle of 100 Tablets"],
    },
    {
      name: "Ibuprofen 400mg Tablet",
      composition: "Ibuprofen",
      strength: "400mg",
      brand: "Abbott",
      basePrice: 38,
      isRx: false,
      forms: ["Strip of 10 Tablets", "Strip of 20 Tablets"],
    },
    {
      name: "Diclofenac 50mg Tablet",
      composition: "Diclofenac Sodium",
      strength: "50mg",
      brand: "Novartis",
      basePrice: 55,
      isRx: true,
      forms: ["Strip of 10 Tablets", "Strip of 15 Tablets"],
    },
    {
      name: "Aceclofenac + Paracetamol Tablet",
      composition: "Aceclofenac + Paracetamol",
      strength: "100mg+325mg",
      brand: "IPCA",
      basePrice: 68,
      isRx: true,
      forms: ["Strip of 10 Tablets", "Strip of 20 Tablets"],
    },
    {
      name: "Naproxen 500mg Tablet",
      composition: "Naproxen Sodium",
      strength: "500mg",
      brand: "Dr. Reddy's",
      basePrice: 72,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Nimesulide 100mg Tablet",
      composition: "Nimesulide",
      strength: "100mg",
      brand: "Cipla",
      basePrice: 30,
      isRx: false,
      forms: ["Strip of 10 Tablets", "Strip of 15 Tablets"],
    },
    {
      name: "Aspirin 75mg Tablet",
      composition: "Aspirin",
      strength: "75mg",
      brand: "Bayer",
      basePrice: 18,
      isRx: false,
      forms: ["Strip of 14 Tablets", "Bottle of 100 Tablets"],
    },
    {
      name: "Ketorolac 10mg Tablet",
      composition: "Ketorolac Tromethamine",
      strength: "10mg",
      brand: "Sun Pharma",
      basePrice: 95,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Mefenamic Acid 250mg Capsule",
      composition: "Mefenamic Acid",
      strength: "250mg",
      brand: "Pfizer",
      basePrice: 42,
      isRx: false,
      forms: ["Strip of 10 Capsules", "Strip of 20 Capsules"],
    },
    {
      name: "Paracetamol 650mg Tablet",
      composition: "Paracetamol",
      strength: "650mg",
      brand: "GSK",
      basePrice: 32,
      isRx: false,
      forms: ["Strip of 15 Tablets"],
    },
    {
      name: "Crocin Advance 500mg",
      composition: "Paracetamol",
      strength: "500mg",
      brand: "GSK",
      basePrice: 29,
      isRx: false,
      forms: ["Strip of 15 Tablets"],
    },
    {
      name: "Combiflam Tablet",
      composition: "Ibuprofen + Paracetamol",
      strength: "400mg+325mg",
      brand: "Sanofi",
      basePrice: 45,
      isRx: false,
      forms: ["Strip of 20 Tablets"],
    },
    {
      name: "Volini Gel 30g",
      composition: "Diclofenac Diethylamine",
      strength: "1%w/w",
      brand: "Sun Pharma",
      basePrice: 120,
      isRx: false,
      forms: ["Tube of 30g"],
    },
    {
      name: "Zerodol SP Tablet",
      composition: "Aceclofenac + Paracetamol + Serratiopeptidase",
      strength: "100mg+325mg+15mg",
      brand: "IPCA",
      basePrice: 88,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Caldikind Plus Tablet",
      composition: "Calcium + Vitamin D3",
      strength: "500mg+250IU",
      brand: "Mankind",
      basePrice: 95,
      isRx: false,
      forms: ["Strip of 15 Tablets"],
    },
  ],
  "diabetes-care": [
    {
      name: "Metformin 500mg Tablet",
      composition: "Metformin Hydrochloride",
      strength: "500mg",
      brand: "USV",
      basePrice: 28,
      isRx: true,
      forms: ["Strip of 10 Tablets", "Bottle of 100 Tablets"],
    },
    {
      name: "Glimepiride 2mg Tablet",
      composition: "Glimepiride",
      strength: "2mg",
      brand: "Sanofi",
      basePrice: 48,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Januvia 100mg Tablet",
      composition: "Sitagliptin",
      strength: "100mg",
      brand: "MSD",
      basePrice: 380,
      isRx: true,
      forms: ["Strip of 7 Tablets", "Strip of 14 Tablets"],
    },
    {
      name: "Dapagliflozin 10mg Tablet",
      composition: "Dapagliflozin",
      strength: "10mg",
      brand: "AstraZeneca",
      basePrice: 295,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Vildagliptin 50mg Tablet",
      composition: "Vildagliptin",
      strength: "50mg",
      brand: "Novartis",
      basePrice: 210,
      isRx: true,
      forms: ["Strip of 14 Tablets"],
    },
    {
      name: "Insulin Glargine 100IU/ml",
      composition: "Insulin Glargine",
      strength: "100IU/ml",
      brand: "Sanofi",
      basePrice: 850,
      isRx: true,
      forms: ["Cartridge of 3ml", "Pen"],
    },
    {
      name: "Glycomet 850mg Tablet",
      composition: "Metformin Hydrochloride",
      strength: "850mg",
      brand: "USV",
      basePrice: 35,
      isRx: true,
      forms: ["Strip of 15 Tablets"],
    },
    {
      name: "Trajenta 5mg Tablet",
      composition: "Linagliptin",
      strength: "5mg",
      brand: "Boehringer",
      basePrice: 310,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Glucobay 50mg Tablet",
      composition: "Acarbose",
      strength: "50mg",
      brand: "Bayer",
      basePrice: 130,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Gliclazide 80mg Tablet",
      composition: "Gliclazide",
      strength: "80mg",
      brand: "Torrent",
      basePrice: 55,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Glucophage 500mg Tablet",
      composition: "Metformin Hydrochloride",
      strength: "500mg",
      brand: "Merck",
      basePrice: 32,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Pioglitazone 15mg Tablet",
      composition: "Pioglitazone",
      strength: "15mg",
      brand: "Sun Pharma",
      basePrice: 68,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Empagliflozin 10mg Tablet",
      composition: "Empagliflozin",
      strength: "10mg",
      brand: "Boehringer",
      basePrice: 280,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Diabetes Monitor Strips",
      composition: "Glucose Testing Strips",
      strength: "N/A",
      brand: "Abbott",
      basePrice: 350,
      isRx: false,
      forms: ["Pack of 50 Strips"],
    },
    {
      name: "Insulin Syringe 1ml",
      composition: "Medical Device",
      strength: "1ml/100IU",
      brand: "BD",
      basePrice: 180,
      isRx: false,
      forms: ["Pack of 10 Syringes"],
    },
  ],
  "respiratory-allergy": [
    {
      name: "Cetirizine 10mg Tablet",
      composition: "Cetirizine Hydrochloride",
      strength: "10mg",
      brand: "Glenmark",
      basePrice: 20,
      isRx: false,
      forms: ["Strip of 10 Tablets", "Strip of 15 Tablets"],
    },
    {
      name: "Montelukast 10mg Tablet",
      composition: "Montelukast Sodium",
      strength: "10mg",
      brand: "Cipla",
      basePrice: 65,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Budesonide 200mcg Inhaler",
      composition: "Budesonide",
      strength: "200mcg",
      brand: "AstraZeneca",
      basePrice: 380,
      isRx: true,
      forms: ["1 Inhaler (200 doses)"],
    },
    {
      name: "Salbutamol 100mcg Inhaler",
      composition: "Salbutamol Sulphate",
      strength: "100mcg",
      brand: "Cipla",
      basePrice: 280,
      isRx: true,
      forms: ["1 Inhaler (200 doses)"],
    },
    {
      name: "Fexofenadine 120mg Tablet",
      composition: "Fexofenadine Hydrochloride",
      strength: "120mg",
      brand: "Sanofi",
      basePrice: 90,
      isRx: false,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Levocetrizine 5mg Tablet",
      composition: "Levocetirizine Dihydrochloride",
      strength: "5mg",
      brand: "Sun Pharma",
      basePrice: 38,
      isRx: false,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Asthalin 100mcg Inhaler",
      composition: "Salbutamol",
      strength: "100mcg",
      brand: "Cipla",
      basePrice: 165,
      isRx: true,
      forms: ["1 Inhaler"],
    },
    {
      name: "Fluticasone Nasal Spray",
      composition: "Fluticasone Propionate",
      strength: "50mcg/spray",
      brand: "GSK",
      basePrice: 290,
      isRx: true,
      forms: ["1 Bottle (150 sprays)"],
    },
    {
      name: "Montelukast + Levocetirizine Tablet",
      composition: "Montelukast + Levocetirizine",
      strength: "10mg+5mg",
      brand: "Cipla",
      basePrice: 85,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Deriphyllin 150mg Tablet",
      composition: "Etofylline + Theophylline",
      strength: "150mg",
      brand: "Win Medicare",
      basePrice: 42,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Ipratropium Inhaler 20mcg",
      composition: "Ipratropium Bromide",
      strength: "20mcg",
      brand: "Boehringer",
      basePrice: 320,
      isRx: true,
      forms: ["1 Inhaler"],
    },
    {
      name: "Zyrtec 10mg Tablet",
      composition: "Cetirizine Hydrochloride",
      strength: "10mg",
      brand: "J&J",
      basePrice: 25,
      isRx: false,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Beclomethasone 100mcg Inhaler",
      composition: "Beclomethasone Dipropionate",
      strength: "100mcg",
      brand: "3M",
      basePrice: 295,
      isRx: true,
      forms: ["1 Inhaler"],
    },
    {
      name: "Azelastine Nasal Spray",
      composition: "Azelastine Hydrochloride",
      strength: "0.1%",
      brand: "Meda",
      basePrice: 210,
      isRx: false,
      forms: ["1 Bottle (100 sprays)"],
    },
    {
      name: "Loratadine 10mg Tablet",
      composition: "Loratadine",
      strength: "10mg",
      brand: "MSD",
      basePrice: 18,
      isRx: false,
      forms: ["Strip of 10 Tablets"],
    },
  ],
  "gut-health": [
    {
      name: "Omeprazole 20mg Capsule",
      composition: "Omeprazole",
      strength: "20mg",
      brand: "AstraZeneca",
      basePrice: 35,
      isRx: false,
      forms: ["Strip of 15 Capsules", "Bottle of 30 Capsules"],
    },
    {
      name: "Pantoprazole 40mg Tablet",
      composition: "Pantoprazole Sodium",
      strength: "40mg",
      brand: "Sun Pharma",
      basePrice: 42,
      isRx: false,
      forms: ["Strip of 15 Tablets"],
    },
    {
      name: "Domperidone 10mg Tablet",
      composition: "Domperidone",
      strength: "10mg",
      brand: "J&J",
      basePrice: 28,
      isRx: false,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Metronidazole 400mg Tablet",
      composition: "Metronidazole",
      strength: "400mg",
      brand: "Cipla",
      basePrice: 22,
      isRx: true,
      forms: ["Strip of 15 Tablets"],
    },
    {
      name: "Ondansetron 4mg Tablet",
      composition: "Ondansetron Hydrochloride",
      strength: "4mg",
      brand: "Zydus",
      basePrice: 55,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Digene Gel 200ml",
      composition: "Aluminum Hydroxide + Magnesium Hydroxide",
      strength: "Mixed",
      brand: "Abbott",
      basePrice: 120,
      isRx: false,
      forms: ["Bottle of 200ml"],
    },
    {
      name: "Lactulose 10g/15ml Syrup",
      composition: "Lactulose",
      strength: "67%w/v",
      brand: "Intas",
      basePrice: 145,
      isRx: false,
      forms: ["Bottle of 150ml"],
    },
    {
      name: "Rabeprazole 20mg Tablet",
      composition: "Rabeprazole Sodium",
      strength: "20mg",
      brand: "Cipla",
      basePrice: 48,
      isRx: false,
      forms: ["Strip of 15 Tablets"],
    },
    {
      name: "Librax Capsule",
      composition: "Chlordiazepoxide + Clidinium",
      strength: "5mg+2.5mg",
      brand: "Roche",
      basePrice: 75,
      isRx: true,
      forms: ["Strip of 10 Capsules"],
    },
    {
      name: "Flagyl 400mg Tablet",
      composition: "Metronidazole",
      strength: "400mg",
      brand: "Sanofi",
      basePrice: 30,
      isRx: true,
      forms: ["Strip of 15 Tablets"],
    },
    {
      name: "Normaxin Tablet",
      composition: "Chlordiazepoxide + Dicyclomine + Clidinium",
      strength: "Mixed",
      brand: "Sun Pharma",
      basePrice: 65,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Enterogermina 2bn Vial",
      composition: "Bacillus clausii",
      strength: "2bn spores/5ml",
      brand: "Sanofi",
      basePrice: 210,
      isRx: false,
      forms: ["Pack of 6 Vials"],
    },
    {
      name: "Dulcolax 5mg Tablet",
      composition: "Bisacodyl",
      strength: "5mg",
      brand: "Boehringer",
      basePrice: 35,
      isRx: false,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Cremaffin Syrup 225ml",
      composition: "Liquid Paraffin + Milk of Magnesia + Sodium Picosulfate",
      strength: "Mixed",
      brand: "Abbott",
      basePrice: 155,
      isRx: false,
      forms: ["Bottle of 225ml"],
    },
    {
      name: "Rennie Antacid Tablet",
      composition: "Calcium Carbonate + Magnesium Carbonate",
      strength: "680mg+80mg",
      brand: "Bayer",
      basePrice: 45,
      isRx: false,
      forms: ["Strip of 12 Tablets"],
    },
  ],
  "vitamins-immunity": [
    {
      name: "Vitamin C 500mg Tablet",
      composition: "Ascorbic Acid",
      strength: "500mg",
      brand: "Pfizer",
      basePrice: 85,
      isRx: false,
      forms: ["Strip of 10 Tablets", "Bottle of 60 Tablets"],
    },
    {
      name: "Vitamin D3 60000IU Capsule",
      composition: "Cholecalciferol",
      strength: "60000IU",
      brand: "Abbott",
      basePrice: 175,
      isRx: false,
      forms: ["Strip of 4 Capsules"],
    },
    {
      name: "Zinc + Vitamin C Tablet",
      composition: "Zinc Sulphate + Vitamin C",
      strength: "22.5mg+500mg",
      brand: "Cipla",
      basePrice: 95,
      isRx: false,
      forms: ["Strip of 15 Tablets"],
    },
    {
      name: "Revital H Capsule",
      composition: "Vitamins + Minerals + Ginseng",
      strength: "Mixed",
      brand: "Abbott",
      basePrice: 310,
      isRx: false,
      forms: ["Strip of 30 Capsules"],
    },
    {
      name: "Becadexamin Capsule",
      composition: "B-Complex + Vitamins A, C, D, E",
      strength: "Mixed",
      brand: "GSK",
      basePrice: 120,
      isRx: false,
      forms: ["Strip of 20 Capsules"],
    },
    {
      name: "Omega-3 Fish Oil 1000mg",
      composition: "Omega-3 Fatty Acids",
      strength: "1000mg",
      brand: "Nordic Naturals",
      basePrice: 350,
      isRx: false,
      forms: ["Bottle of 30 Capsules", "Bottle of 60 Capsules"],
    },
    {
      name: "Iron + Folic Acid Tablet",
      composition: "Ferrous Sulphate + Folic Acid",
      strength: "150mg+0.5mg",
      brand: "Himalaya",
      basePrice: 55,
      isRx: false,
      forms: ["Strip of 30 Tablets"],
    },
    {
      name: "Calcium Sandoz 500mg Tablet",
      composition: "Calcium Lactogluconate",
      strength: "500mg",
      brand: "Sandoz",
      basePrice: 145,
      isRx: false,
      forms: ["Strip of 20 Tablets"],
    },
    {
      name: "B12 Methylcobalamin 500mcg",
      composition: "Methylcobalamin",
      strength: "500mcg",
      brand: "Sun Pharma",
      basePrice: 68,
      isRx: false,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Chyawanprash 1kg",
      composition: "Herbal Blend",
      strength: "Mixed",
      brand: "Dabur",
      basePrice: 280,
      isRx: false,
      forms: ["Jar of 1kg"],
    },
    {
      name: "Neurobion Forte Tablet",
      composition: "B1+B2+B6+B12+Niacin+Pantothenic Acid",
      strength: "Mixed",
      brand: "Merck",
      basePrice: 72,
      isRx: false,
      forms: ["Strip of 30 Tablets"],
    },
    {
      name: "Supradyn Daily Multivitamin",
      composition: "13 Vitamins + 13 Minerals",
      strength: "Mixed",
      brand: "Bayer",
      basePrice: 220,
      isRx: false,
      forms: ["Strip of 15 Tablets"],
    },
    {
      name: "Ashwagandha KSM-66 300mg",
      composition: "Withania somnifera Extract",
      strength: "300mg",
      brand: "Himalaya",
      basePrice: 195,
      isRx: false,
      forms: ["Bottle of 60 Capsules"],
    },
    {
      name: "Glucosamine + Chondroitin Tablet",
      composition: "Glucosamine Sulphate + Chondroitin",
      strength: "500mg+400mg",
      brand: "Solgar",
      basePrice: 420,
      isRx: false,
      forms: ["Strip of 30 Tablets"],
    },
    {
      name: "Probiotic 10 Billion CFU Capsule",
      composition: "Lactobacillus acidophilus + Bifidobacterium",
      strength: "10 billion CFU",
      brand: "UB Flora",
      basePrice: 280,
      isRx: false,
      forms: ["Bottle of 30 Capsules"],
    },
  ],
  "skin-personal-care": [
    {
      name: "Cetaphil Gentle Skin Cleanser 250ml",
      composition: "Glycerin + Niacinamide",
      strength: "Mixed",
      brand: "Cetaphil",
      basePrice: 380,
      isRx: false,
      forms: ["Bottle of 250ml"],
    },
    {
      name: "Betnovate Cream 20g",
      composition: "Betamethasone Valerate",
      strength: "0.1%w/w",
      brand: "GSK",
      basePrice: 65,
      isRx: true,
      forms: ["Tube of 20g"],
    },
    {
      name: "Candid B Cream 20g",
      composition: "Beclomethasone + Clotrimazole",
      strength: "0.025%+1%",
      brand: "Glenmark",
      basePrice: 72,
      isRx: true,
      forms: ["Tube of 20g"],
    },
    {
      name: "Sunscreen SPF 50 PA++ 75ml",
      composition: "Zinc Oxide + Titanium Dioxide",
      strength: "SPF 50",
      brand: "La Roche-Posay",
      basePrice: 650,
      isRx: false,
      forms: ["Tube of 75ml"],
    },
    {
      name: "Soframycin Skin Cream 25g",
      composition: "Framycetin Sulphate",
      strength: "1%w/w",
      brand: "Roussel",
      basePrice: 65,
      isRx: false,
      forms: ["Tube of 25g"],
    },
    {
      name: "Retino-A 0.025% Cream 20g",
      composition: "Tretinoin",
      strength: "0.025%",
      brand: "Janssen",
      basePrice: 110,
      isRx: true,
      forms: ["Tube of 20g"],
    },
    {
      name: "Clindac A Gel 15g",
      composition: "Clindamycin Phosphate",
      strength: "1%w/w",
      brand: "Galderma",
      basePrice: 145,
      isRx: true,
      forms: ["Tube of 15g"],
    },
    {
      name: "Nizoral Shampoo 100ml",
      composition: "Ketoconazole",
      strength: "2%w/v",
      brand: "J&J",
      basePrice: 220,
      isRx: false,
      forms: ["Bottle of 100ml"],
    },
    {
      name: "Clobetasol 0.05% Cream",
      composition: "Clobetasol Propionate",
      strength: "0.05%",
      brand: "Sun Pharma",
      basePrice: 88,
      isRx: true,
      forms: ["Tube of 15g", "Tube of 30g"],
    },
    {
      name: "Eumosone M Cream 20g",
      composition: "Clobetasol + Miconazole + Neomycin",
      strength: "Mixed",
      brand: "Piramal",
      basePrice: 95,
      isRx: true,
      forms: ["Tube of 20g"],
    },
    {
      name: "Kojivit Plus Gel 20g",
      composition: "Kojic Acid + Arbutin + Vitamin C",
      strength: "Mixed",
      brand: "Micro Labs",
      basePrice: 220,
      isRx: false,
      forms: ["Tube of 20g"],
    },
    {
      name: "Acne Star Gel 15g",
      composition: "Benzoyl Peroxide + Clindamycin",
      strength: "2.5%+1%",
      brand: "Elder",
      basePrice: 165,
      isRx: false,
      forms: ["Tube of 15g"],
    },
    {
      name: "Moisturex Soft Cream 150g",
      composition: "Urea + Lactic Acid",
      strength: "Mixed",
      brand: "Piramal",
      basePrice: 185,
      isRx: false,
      forms: ["Tube of 150g"],
    },
    {
      name: "Tacrolimus 0.03% Ointment 10g",
      composition: "Tacrolimus",
      strength: "0.03%w/w",
      brand: "Fujisawa",
      basePrice: 390,
      isRx: true,
      forms: ["Tube of 10g"],
    },
    {
      name: "Mometasone Furoate Cream",
      composition: "Mometasone Furoate",
      strength: "0.1%",
      brand: "Schering",
      basePrice: 120,
      isRx: true,
      forms: ["Tube of 15g", "Tube of 30g"],
    },
  ],
  "baby-mother-care": [
    {
      name: "Gripe Water 100ml",
      composition: "Dill Seed Oil + Sodium Bicarbonate",
      strength: "Mixed",
      brand: "Woodward's",
      basePrice: 65,
      isRx: false,
      forms: ["Bottle of 100ml"],
    },
    {
      name: "Cerelac Rice 1kg",
      composition: "Infant Cereal",
      strength: "Stage 1",
      brand: "Nestle",
      basePrice: 390,
      isRx: false,
      forms: ["Tin of 1kg"],
    },
    {
      name: "Folic Acid 5mg Tablet",
      composition: "Folic Acid",
      strength: "5mg",
      brand: "Sun Pharma",
      basePrice: 35,
      isRx: true,
      forms: ["Strip of 30 Tablets"],
    },
    {
      name: "Calcimax Forte Tablet",
      composition: "Calcium + Vitamin D3 + Magnesium",
      strength: "Mixed",
      brand: "Meyer",
      basePrice: 185,
      isRx: false,
      forms: ["Strip of 30 Tablets"],
    },
    {
      name: "Doxinate Tablet",
      composition: "Doxylamine + Pyridoxine",
      strength: "10mg+10mg",
      brand: "Alkem",
      basePrice: 95,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Neopeptine Drops 15ml",
      composition: "Fungal Diastase + Papain",
      strength: "Mixed",
      brand: "Jagsonpal",
      basePrice: 78,
      isRx: false,
      forms: ["Bottle of 15ml"],
    },
    {
      name: "Lactogen 1 Infant Formula 400g",
      composition: "Whey Protein + Vitamins",
      strength: "Stage 1",
      brand: "Nestle",
      basePrice: 425,
      isRx: false,
      forms: ["Tin of 400g"],
    },
    {
      name: "Colicaid Drops 15ml",
      composition: "Simethicone + Fennel",
      strength: "Mixed",
      brand: "Mankind",
      basePrice: 72,
      isRx: false,
      forms: ["Bottle of 15ml"],
    },
    {
      name: "Softovac Bowel Regulator 100g",
      composition: "Isabgol + Senna",
      strength: "Mixed",
      brand: "Lupin",
      basePrice: 130,
      isRx: false,
      forms: ["Sachet Pack of 100g"],
    },
    {
      name: "Prenatal Multivitamin Tablet",
      composition: "Complete Prenatal Vitamins",
      strength: "Mixed",
      brand: "Abbott",
      basePrice: 320,
      isRx: false,
      forms: ["Strip of 30 Tablets"],
    },
    {
      name: "Drools Milkis Powder 1kg",
      composition: "Infant Formula",
      strength: "Stage 2",
      brand: "Drools",
      basePrice: 345,
      isRx: false,
      forms: ["Bag of 1kg"],
    },
    {
      name: "Winolap Nasal Drop 5ml",
      composition: "Xylometazoline",
      strength: "0.05%w/v",
      brand: "Glenmark",
      basePrice: 48,
      isRx: false,
      forms: ["Bottle of 5ml"],
    },
    {
      name: "Pedialyte ORS 1L",
      composition: "Oral Rehydration Salts",
      strength: "WHO Formula",
      brand: "Abbott",
      basePrice: 85,
      isRx: false,
      forms: ["Sachet (1L mix)"],
    },
    {
      name: "Johnson Baby Powder 200g",
      composition: "Talc + Zinc Oxide",
      strength: "Mixed",
      brand: "J&J",
      basePrice: 145,
      isRx: false,
      forms: ["Bottle of 200g"],
    },
    {
      name: "Safi Herbal Tonic 200ml",
      composition: "Herbal Blend (Chandan, Senna, etc.)",
      strength: "Mixed",
      brand: "Hamdard",
      basePrice: 120,
      isRx: false,
      forms: ["Bottle of 200ml"],
    },
  ],
  "medical-devices": [
    {
      name: "Blood Glucose Monitor",
      composition: "Glucometer",
      strength: "N/A",
      brand: "Accu-Chek",
      basePrice: 1200,
      isRx: false,
      forms: ["1 Device + Lancets + Strips"],
    },
    {
      name: "Digital Thermometer",
      composition: "Electronic Thermometer",
      strength: "Range 32-42°C",
      brand: "Omron",
      basePrice: 350,
      isRx: false,
      forms: ["1 Unit"],
    },
    {
      name: "Blood Pressure Monitor",
      composition: "Automatic BP Monitor",
      strength: "Upper Arm",
      brand: "Omron",
      basePrice: 2800,
      isRx: false,
      forms: ["1 Device + Cuff"],
    },
    {
      name: "Pulse Oximeter",
      composition: "SpO2 Monitor",
      strength: "90-100% Range",
      brand: "Contec",
      basePrice: 950,
      isRx: false,
      forms: ["1 Unit"],
    },
    {
      name: "Nebulizer Machine",
      composition: "Compressor Nebulizer",
      strength: "N/A",
      brand: "Philips",
      basePrice: 3500,
      isRx: false,
      forms: ["1 Unit + Accessories"],
    },
    {
      name: "Orthopedic Knee Cap",
      composition: "Elastic Knee Support",
      strength: "Medium",
      brand: "Tynor",
      basePrice: 380,
      isRx: false,
      forms: ["1 Pair", "Single"],
    },
    {
      name: "Surgical Gloves (M) Pack of 50",
      composition: "Latex / Nitrile",
      strength: "Size M",
      brand: "Kimberly-Clark",
      basePrice: 280,
      isRx: false,
      forms: ["Pack of 50 pairs"],
    },
    {
      name: "Disposable Syringe 5ml",
      composition: "Medical Grade Plastic",
      strength: "5ml",
      brand: "BD",
      basePrice: 120,
      isRx: false,
      forms: ["Pack of 10"],
    },
    {
      name: "Digital Peak Flow Meter",
      composition: "Spirometry Device",
      strength: "N/A",
      brand: "Micro Medical",
      basePrice: 1800,
      isRx: false,
      forms: ["1 Device"],
    },
    {
      name: "Wheelchair Standard",
      composition: "Steel Frame Wheelchair",
      strength: "100kg Load",
      brand: "Vissco",
      basePrice: 6500,
      isRx: false,
      forms: ["1 Unit"],
    },
    {
      name: "Heating Pad Electric",
      composition: "Electric Thermal Pad",
      strength: "50W",
      brand: "Healthgenie",
      basePrice: 650,
      isRx: false,
      forms: ["1 Pad"],
    },
    {
      name: "Crepe Bandage 8cm",
      composition: "Cotton Elastic Bandage",
      strength: "8cm x 4m",
      brand: "Surgilast",
      basePrice: 58,
      isRx: false,
      forms: ["1 Roll", "Pack of 5 Rolls"],
    },
    {
      name: "Micropore Tape 2.5cm",
      composition: "Surgical Paper Tape",
      strength: "2.5cm x 9.1m",
      brand: "3M",
      basePrice: 95,
      isRx: false,
      forms: ["1 Roll"],
    },
    {
      name: "Glucometer Test Strips (50)",
      composition: "Glucose Oxidase Strips",
      strength: "50 strips",
      brand: "Accu-Chek",
      basePrice: 680,
      isRx: false,
      forms: ["Pack of 50"],
    },
    {
      name: "Lancets for Glucometer (100)",
      composition: "Sterile Lancets",
      strength: "28G",
      brand: "BD",
      basePrice: 290,
      isRx: false,
      forms: ["Pack of 100"],
    },
  ],
  "pain-relief": [
    {
      name: "Voltaren Emulgel 100g",
      composition: "Diclofenac Diethylamine",
      strength: "1.16%",
      brand: "Novartis",
      basePrice: 280,
      isRx: false,
      forms: ["Tube of 100g"],
    },
    {
      name: "Tramadol 50mg Capsule",
      composition: "Tramadol Hydrochloride",
      strength: "50mg",
      brand: "Grunenthal",
      basePrice: 85,
      isRx: true,
      forms: ["Strip of 10 Capsules"],
    },
    {
      name: "Pregabalin 75mg Capsule",
      composition: "Pregabalin",
      strength: "75mg",
      brand: "Pfizer",
      basePrice: 150,
      isRx: true,
      forms: ["Strip of 10 Capsules"],
    },
    {
      name: "Muscle Pain Relief Spray",
      composition: "Methyl Salicylate + Menthol",
      strength: "Mixed",
      brand: "Amrutanjan",
      basePrice: 145,
      isRx: false,
      forms: ["Spray 100ml"],
    },
    {
      name: "Lidocaine 2% Gel",
      composition: "Lignocaine Hydrochloride",
      strength: "2%",
      brand: "Astra",
      basePrice: 65,
      isRx: true,
      forms: ["Tube of 30g"],
    },
    {
      name: "Celebrex 200mg Capsule",
      composition: "Celecoxib",
      strength: "200mg",
      brand: "Pfizer",
      basePrice: 180,
      isRx: true,
      forms: ["Strip of 10 Capsules"],
    },
    {
      name: "Morphine Sulphate 10mg Tablet",
      composition: "Morphine Sulphate",
      strength: "10mg",
      brand: "Sanofi",
      basePrice: 95,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Zaldiar Tablet",
      composition: "Tramadol + Paracetamol",
      strength: "37.5mg+325mg",
      brand: "Grunenthal",
      basePrice: 120,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Moov Cream 50g",
      composition: "Diclofenac + Methyl Salicylate + Menthol",
      strength: "Mixed",
      brand: "Reckitt",
      basePrice: 95,
      isRx: false,
      forms: ["Tube of 50g"],
    },
    {
      name: "Counterpain Analgesic Balm",
      composition: "Methyl Salicylate + Menthol + Eucalyptus",
      strength: "Mixed",
      brand: "Taisho",
      basePrice: 120,
      isRx: false,
      forms: ["Tube of 60g"],
    },
    {
      name: "Ibuprofen 600mg Tablet",
      composition: "Ibuprofen",
      strength: "600mg",
      brand: "Cipla",
      basePrice: 52,
      isRx: false,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Piroxicam 20mg Capsule",
      composition: "Piroxicam",
      strength: "20mg",
      brand: "Pfizer",
      basePrice: 45,
      isRx: true,
      forms: ["Strip of 10 Capsules"],
    },
    {
      name: "Tiger Balm Regular 19.4g",
      composition: "Camphor + Menthol + Cajuput Oil",
      strength: "Mixed",
      brand: "Tiger Balm",
      basePrice: 165,
      isRx: false,
      forms: ["Jar of 19.4g"],
    },
    {
      name: "Etoricoxib 60mg Tablet",
      composition: "Etoricoxib",
      strength: "60mg",
      brand: "MSD",
      basePrice: 145,
      isRx: true,
      forms: ["Strip of 7 Tablets"],
    },
    {
      name: "TENS Machine Pain Reliever",
      composition: "Transcutaneous Electrical Nerve Stimulator",
      strength: "N/A",
      brand: "Omron",
      basePrice: 1850,
      isRx: false,
      forms: ["1 Device"],
    },
  ],
  respiratory: [
    {
      name: "Asthalin Respules 2.5mg",
      composition: "Salbutamol Sulphate",
      strength: "2.5mg/2.5ml",
      brand: "Cipla",
      basePrice: 85,
      isRx: true,
      forms: ["Strip of 5 Respules"],
    },
    {
      name: "Seroflo 250 Inhaler",
      composition: "Salmeterol + Fluticasone",
      strength: "25mcg+250mcg",
      brand: "Cipla",
      basePrice: 520,
      isRx: true,
      forms: ["1 Inhaler (120 doses)"],
    },
    {
      name: "Tiova Inhaler 18mcg",
      composition: "Tiotropium Bromide",
      strength: "18mcg",
      brand: "Cipla",
      basePrice: 380,
      isRx: true,
      forms: ["1 Inhaler (60 doses)"],
    },
    {
      name: "Tusq D Plus Syrup 100ml",
      composition: "Dextromethorphan + Phenylephrine",
      strength: "Mixed",
      brand: "Panacea",
      basePrice: 68,
      isRx: false,
      forms: ["Bottle of 100ml"],
    },
    {
      name: "Mucinex 600mg Tablet",
      composition: "Guaifenesin",
      strength: "600mg",
      brand: "Reckitt",
      basePrice: 145,
      isRx: false,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Ventolin Nebuliser 2.5mg",
      composition: "Salbutamol",
      strength: "2.5mg/2.5ml",
      brand: "GSK",
      basePrice: 95,
      isRx: true,
      forms: ["Pack of 5 Respules"],
    },
    {
      name: "Formoterol 12mcg Inhaler",
      composition: "Formoterol Fumarate",
      strength: "12mcg",
      brand: "AstraZeneca",
      basePrice: 450,
      isRx: true,
      forms: ["1 Inhaler"],
    },
    {
      name: "Theophylline SR 300mg Tablet",
      composition: "Theophylline",
      strength: "300mg",
      brand: "Wockhardt",
      basePrice: 55,
      isRx: true,
      forms: ["Strip of 30 Tablets"],
    },
    {
      name: "Combivent Nebulysation",
      composition: "Ipratropium + Salbutamol",
      strength: "0.5mg+2.5mg",
      brand: "Boehringer",
      basePrice: 175,
      isRx: true,
      forms: ["Pack of 25 Vials"],
    },
    {
      name: "N-Acetylcysteine 600mg Effervescent",
      composition: "N-Acetylcysteine",
      strength: "600mg",
      brand: "Cipla",
      basePrice: 95,
      isRx: false,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Montelukast 5mg Chewable Tablet",
      composition: "Montelukast Sodium",
      strength: "5mg",
      brand: "MSD",
      basePrice: 92,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Codeine Phosphate 10mg Tablet",
      composition: "Codeine Phosphate",
      strength: "10mg",
      brand: "Kaizen",
      basePrice: 45,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Prednisolone 10mg Tablet",
      composition: "Prednisolone",
      strength: "10mg",
      brand: "Sun Pharma",
      basePrice: 35,
      isRx: true,
      forms: ["Strip of 10 Tablets"],
    },
    {
      name: "Bisolvon Expectorant 100ml",
      composition: "Bromhexine Hydrochloride",
      strength: "4mg/5ml",
      brand: "Boehringer",
      basePrice: 72,
      isRx: false,
      forms: ["Bottle of 100ml"],
    },
    {
      name: "Medicinal Oxygen 1L Cylinder",
      composition: "Medical Grade Oxygen",
      strength: "99.5% purity",
      brand: "OXY99",
      basePrice: 890,
      isRx: false,
      forms: ["1 Cylinder"],
    },
  ],
};

function makeProducts(categoryId, slug) {
  const templates = CATEGORY_PRODUCTS[slug] || [];
  const results = [];
  let idx = 1;

  for (const t of templates) {
    for (const packSize of t.forms) {
      const priceVariance = 0.9 + Math.random() * 0.25; // ±12% variance
      const price = Math.round(t.basePrice * priceVariance);
      const mrp = Math.round(price * (1.1 + Math.random() * 0.1));
      const stock = Math.floor(Math.random() * 200) + 30;

      results.push({
        name: `${t.name} (${packSize})`,
        brand: t.brand,
        composition: t.composition,
        strength: t.strength,
        packSize,
        price,
        mrp,
        prescriptionRequired: t.isRx,
        isRx: t.isRx,
        requiresRx: t.isRx,
        stock,
        category: categoryId,
        images: ["https://via.placeholder.com/300x300?text=Medicine"],
        sku: `FIX-${slug.toUpperCase().slice(0, 6)}-${String(idx).padStart(4, "0")}`,
      });
      idx++;
    }
  }
  return results;
}

async function run() {
  await mongoose.connect(MONGO_URI);
  console.log("✅ Connected to MongoDB");

  // 1. Fix price=0 products — find and bulk write with JS random prices
  const zeroPricedIds = await Product.find(
    { price: { $lte: 0 } },
    "_id",
  ).lean();
  if (zeroPricedIds.length > 0) {
    const bulkOps = zeroPricedIds.map((doc) => ({
      updateOne: {
        filter: { _id: doc._id },
        update: { $set: { price: Math.floor(15 + Math.random() * 485) } },
      },
    }));
    const bwResult = await Product.bulkWrite(bulkOps);
    console.log(`💰 Fixed prices for ${bwResult.modifiedCount} products`);
  } else {
    console.log("✅ No zero-price products remaining");
  }

  // 2. Seed empty categories
  const allCategories = await Category.find().lean();
  let totalInserted = 0;

  for (const cat of allCategories) {
    const count = await Product.countDocuments({ category: cat._id });
    if (count > 0) {
      console.log(`✅ ${cat.slug} already has ${count} products — skipping`);
      continue;
    }

    const docs = makeProducts(cat._id, cat.slug);
    if (docs.length === 0) {
      console.log(`⚠️  No templates for slug: ${cat.slug} — skipping`);
      continue;
    }

    await Product.insertMany(docs, { ordered: false });
    console.log(`🌱 Seeded ${docs.length} products for ${cat.slug}`);
    totalInserted += docs.length;
  }

  console.log(`\n✨ Done! Total new products inserted: ${totalInserted}`);
  await mongoose.disconnect();
}

run().catch((err) => {
  console.error("❌ Fatal error:", err);
  process.exit(1);
});
